# Neighborhood Computations

In [1]:
import numpy as np
import igl
import meshplot

In [2]:
bunny_v, bunny_f = igl.read_triangle_mesh("data/bunny.off")
cube_v, cube_f = igl.read_triangle_mesh("data/cube.obj")
sphere_v, sphere_f = igl.read_triangle_mesh("data/sphere.obj")

In [3]:
meshplot.plot(bunny_v, bunny_f)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [4]:
meshplot.plot(cube_v, cube_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [5]:
meshplot.plot(sphere_v, sphere_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

## Vertex-to-Face Relations

In [18]:
V=bunny_v
F=bunny_f
vf,ni =igl.vertex_triangle_adjacency(F,V.shape[0])

In [24]:
adjacency_list = [[] for _ in range(V.shape[0])]

    # Populate the adjacency list
for i in range(V.shape[0]):
    start = ni[i]
    end = ni[i + 1]
    adjacency_list[i] = vf[start:end].tolist()
print(adjacency_list)
comparelist1 = [len(inner_list) for inner_list in adjacency_list]

[[849, 850, 912, 944, 945], [738, 788, 1278, 1833], [248, 2795, 2857, 2972, 3408], [911, 912, 945, 960, 974, 991], [971, 2977, 2984, 3012, 3013], [1455, 1658, 1706, 2471, 4816, 4884], [1906, 2443, 2506, 2518, 2526], [5, 15, 103, 2576, 2697, 2799], [55, 118, 144, 2711, 3005], [2599, 2729, 2805, 2945, 3066], [96, 941, 2736, 2773, 2803, 2832, 3164, 3165], [13, 96, 1082, 1689, 2736, 3137, 3143], [1689, 3137, 3816, 3911], [1037, 1053, 1054, 1087, 1122, 1133, 1134], [90, 107, 123, 139], [1017, 1036, 1053, 1074, 1121, 1122], [712, 713, 728, 737, 750, 1970, 2034], [680, 713, 728, 3078], [407, 515, 2113, 2114, 2246, 2335, 3402], [99, 100, 164, 209, 884, 886, 984], [409, 410, 411, 1540, 3177, 3178, 3237], [410, 411, 476, 1318, 1432, 4921, 5709], [2341, 2654, 2657, 3021, 3030, 3043], [789, 1508, 2944, 3009, 3018, 3046], [850, 851, 913, 931, 944], [191, 217, 219, 1090, 1758, 6015, 6456], [915, 1468, 1538, 1547, 1777, 3003], [2816, 2829, 2830, 2858, 2869, 2962], [2780, 2858, 2868, 2869, 4105, 4670]

## Vertex-to-Vertex Relations

In [25]:
a = igl.adjacency_list(F)
print(a)
comparelist2 = [len(inner_list) for inner_list in a]

[[3, 24, 308, 525, 542], [415, 549, 551, 596], [134, 287, 465, 497, 1308], [0, 246, 308, 510, 525, 543], [406, 1235, 1368, 1371, 1375], [792, 917, 1113, 3426, 3454, 3482], [484, 1130, 1163, 1179, 1191], [1236, 1267, 1352, 1381, 1382, 2146], [74, 1325, 1365, 1402, 1420], [280, 465, 1225, 1227, 1259], [11, 349, 451, 1319, 1524, 1537, 1565, 1671], [10, 12, 349, 1413, 1524, 1542, 1693], [11, 1542, 1693, 1724], [15, 238, 246, 266, 292, 526, 543], [156, 390, 440, 889], [13, 480, 503, 511, 526, 543], [17, 294, 324, 549, 551, 796, 1217], [16, 103, 324, 1217], [1547, 1598, 2014, 2034, 2053, 2070, 2085], [267, 343, 378, 506, 1436, 1450, 1451], [21, 34, 571, 1466, 1467, 1484, 1508], [20, 34, 56, 57, 58, 571, 594], [104, 295, 961, 1022, 1224, 1374], [350, 415, 740, 741, 1441, 1442], [0, 265, 291, 308, 542], [31, 36, 37, 38, 559, 568, 3324], [269, 337, 584, 622, 726, 771], [28, 1244, 1310, 1403, 1410, 1428], [27, 1236, 1410, 1428, 2136, 2146], [314, 1208, 1228, 1331, 1335, 1355], [43, 79, 80, 573, 

In [27]:
if(comparelist1==comparelist2) :
    print(True)

True


## Shading

Meshplot requires per vertex normals, so we need to "explode" the mesh

In [8]:
p = meshplot.plot(v, f, n=n, shading={"flat": False})
p.add_lines(v, v + 0.01*n)

array([[-0.5, -0.5,  0.5],
       [ 0.5, -0.5,  0.5],
       [-0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5],
       [-0.5,  0.5, -0.5],
       [ 0.5,  0.5, -0.5],
       [-0.5, -0.5, -0.5],
       [ 0.5, -0.5, -0.5]])

In [32]:
p = meshplot.plot(v, f, n=n, shading={"flat": False})
p.add_lines(v, v + 0.01*n)

NameError: name 'n' is not defined

### Flat Shading

In [231]:
v,f=sphere_v, sphere_f
n=igl.per_face_normals(v,f,np.array([0.,0.,0.]))
colors = np.ones((f.shape[0], 3))*2

explode_v=np.zeros((f.size,3))
explode_f=np.arange(f.size).reshape((-1,3))
explode_normals=np.zeros_like(explode_v)
for (i,k) in enumerate(f):
    for (j,l) in enumerate(k):
        explode_v[i*3+j]=v[l]
        explode_normals[i*3+j]=n[i]


#print(explode_v.shape)
#print(explode_normals.shape)

p=meshplot.plot(explode_v, explode_f,n=explode_normals,shading={"flat": False,"colormap": 'Greys'})
p.add_lines(explode_v, explode_v + 0.1*explode_normals)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1

In [232]:
v,f=cube_v, cube_f
n=igl.per_face_normals(v,f,np.array([0.,0.,0.]))
colors = np.ones((f.shape[0], 3))*2

explode_v=np.zeros((f.size,3))
explode_f=np.arange(f.size).reshape((-1,3))
explode_normals=np.zeros_like(explode_v)
for (i,k) in enumerate(f):
    for (j,l) in enumerate(k):
        explode_v[i*3+j]=v[l]
        explode_normals[i*3+j]=n[i]


#print(explode_v.shape)
#print(explode_normals.shape)

p=meshplot.plot(explode_v, explode_f,n=explode_normals,shading={"flat": False,"colormap": 'Greys'})
p.add_lines(explode_v, explode_v + 0.1*explode_normals)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1

### Per-vertex Shading

In [242]:
v,f=cube_v, cube_f
n=igl.per_vertex_normals(v,f)
colors = np.ones((f.shape[0], 3))*2

explode_v=np.zeros((f.size,3))
explode_f=np.arange(f.size).reshape((-1,3))
explode_normals=np.zeros_like(explode_v)
for (i,k) in enumerate(f):
    for (j,l) in enumerate(k):
        explode_v[i*3+j]=v[l]
        explode_normals[i*3+j]=n[l]


#print(explode_v.shape)
#print(explode_normals)

p=meshplot.plot(explode_v, explode_f,n=explode_normals,shading={"flat": False,"colormap": 'Greys'})
p.add_lines(explode_v, explode_v + 0.1*explode_normals)

(36, 3)
[[-0.66666667 -0.66666667  0.33333333]
 [ 0.40824829 -0.40824829  0.81649658]
 [-0.40824829  0.40824829  0.81649658]
 [-0.40824829  0.40824829  0.81649658]
 [ 0.40824829 -0.40824829  0.81649658]
 [ 0.66666667  0.66666667  0.33333333]
 [-0.40824829  0.40824829  0.81649658]
 [ 0.66666667  0.66666667  0.33333333]
 [-0.66666667  0.66666667 -0.33333333]
 [-0.66666667  0.66666667 -0.33333333]
 [ 0.66666667  0.66666667  0.33333333]
 [ 0.40824829  0.40824829 -0.81649658]
 [-0.66666667  0.66666667 -0.33333333]
 [ 0.40824829  0.40824829 -0.81649658]
 [-0.40824829 -0.40824829 -0.81649658]
 [-0.40824829 -0.40824829 -0.81649658]
 [ 0.40824829  0.40824829 -0.81649658]
 [ 0.66666667 -0.66666667 -0.33333333]
 [-0.40824829 -0.40824829 -0.81649658]
 [ 0.66666667 -0.66666667 -0.33333333]
 [-0.66666667 -0.66666667  0.33333333]
 [-0.66666667 -0.66666667  0.33333333]
 [ 0.66666667 -0.66666667 -0.33333333]
 [ 0.40824829 -0.40824829  0.81649658]
 [ 0.40824829 -0.40824829  0.81649658]
 [ 0.66666667 -0.

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1

In [249]:
v,f=sphere_v, sphere_f
n=igl.per_vertex_normals(v,f)
colors = np.ones((f.shape[0], 3))*2

explode_v=np.zeros((f.size,3))
explode_f=np.arange(f.size).reshape((-1,3))
explode_normals=np.zeros_like(explode_v)
for (i,k) in enumerate(f):
    for (j,l) in enumerate(k):
        explode_v[i*3+j]=v[l]
        explode_normals[i*3+j]=n[l]


#print(explode_v.shape)
#print(explode_normals.shape)

p=meshplot.plot(explode_v, explode_f,n=explode_normals,shading={"flat": False,"colormap": 'Greys'})
p.add_lines(explode_v, explode_v + 0.1*explode_normals)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1

### Per-corner Shading

In [252]:
v,f=cube_v, cube_f
n=igl.per_corner_normals(v,f,90)
colors = np.ones((f.shape[0], 3))*2

explode_v=np.zeros((f.size,3))
explode_f=np.arange(f.size).reshape((-1,3))
explode_normals=np.zeros_like(explode_v)
for (i,k) in enumerate(f):
    for (j,l) in enumerate(k):
        explode_v[i*3+j]=v[l]
        explode_normals[i*3+j]=n[i*3+j]


#print(explode_v.shape)
#print(explode_normals.shape)

p=meshplot.plot(explode_v, explode_f,n=explode_normals,shading={"flat": False,"colormap": 'Greys'})
p.add_lines(explode_v, explode_v + 0.1*explode_normals)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1

In [256]:
v,f=sphere_v, sphere_f
n=igl.per_corner_normals(v,f,90)
colors = np.ones((f.shape[0], 3))*2

explode_v=np.zeros((f.size,3))
explode_f=np.arange(f.size).reshape((-1,3))
explode_normals=np.zeros_like(explode_v)
for (i,k) in enumerate(f):
    for (j,l) in enumerate(k):
        explode_v[i*3+j]=v[l]
        explode_normals[i*3+j]=n[i*3+j]


#print(explode_v.shape)
#print(explode_normals.shape)

p=meshplot.plot(explode_v, explode_f,n=explode_normals,shading={"flat": False,"colormap": 'Greys'})
p.add_lines(explode_v, explode_v + 0.1*explode_normals)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1

## Connected Components

In [269]:
car_v, car_f = igl.read_triangle_mesh("data/car.off")
meshplot.plot(car_v,car_f)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-7.194198…

In [273]:
car_v, car_f = igl.read_triangle_mesh("data/car.off")
components=igl.facet_components(car_f)
colormask=np.linspace(0.0,1.0,components[-1]+1)
colors=np.zeros((car_f.shape[0]))
print(components.shape)
print(colors.shape)
for i in range(car_f.shape[0]):
    colors[i]=colormask[components[i]]
meshplot.plot(car_v,car_f,c=colors)


(20218,)
(20218,)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-7.194198…

In [274]:
coffeecup_v, coffeecup_f = igl.read_triangle_mesh("data/coffeecup.off")
v,f=coffeecup_v,coffeecup_f
components=igl.facet_components(f)
colormask=np.linspace(0.0,1.0,components[-1]+1)
colors=np.zeros((f.shape[0]))
print(components.shape)
print(colors.shape)
for i in range(f.shape[0]):
    colors[i]=colormask[components[i]]
meshplot.plot(v,f,c=colors)


(5664,)
(5664,)


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-3.253649…

## A simple subdivision scheme

In [12]:
import numpy as np
import igl
import meshplot
sphere_v, sphere_f = igl.read_triangle_mesh("data/sphere.obj")
v,f=sphere_v, sphere_f
meshplot.subplot(v,f,s=np.array([2,1,0]))
m_f=igl.barycenter(v,f)
adj_list=igl.adjacency_list(f)
p=np.zeros_like(v)
print(p.shape)
for (i,adj) in enumerate(adj_list):
    a_n=(4 - 2 * np.cos(2 * np.pi / len(adj))) / 9
    p[i]=(1-a_n)*v[i]+ a_n*np.sum(v[adj],axis=0)/len(adj)

(382, 3)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(3,)
(